### PR TITLE
Revendor gardener to get a fix for the missing OSC status fields

### LINKED ISSUE #39: Failing to populate the command, cloudConfig and units in the OSC status
**How to categorize this issue?**

/area os
/kind bug
/priority 3
/os ubuntu

**What happened**:
Shoot creation is failing with 
```
Error while waiting for OperatingSystemConfig shoot--foo--bar/cloud-config-worker-1-a93d4-downloader to become ready: no cloud config information provided in status.
```

For some reason, the OSC status is not updated properly here https://github.com/gardener/gardener-extension-os-ubuntu/blob/168ece194e252c02bfaf7ecfe867ef7dedf44ac5/vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/reconciler.go#L146 even though the resource is successfully reconciled by the extension. There is no error also in the extension's logs.

**What you expected to happen**:
The osc.status.cloudConfig to be properly populated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): master
- Extension version: 168ece194e252c02bfaf7ecfe867ef7dedf44ac5
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Observed on Alicloud and OpenStack, but most probably is not cloud specific.
- Others:

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/kind bug
/os ubuntu

**What this PR does / why we need it**:
Revendor gardener to get a fix for the missing OSC status fields

**Which issue(s) this PR fixes**:
Fixes #39

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug that was preventing the fields `operatingSystemConfig.status.{cloudConfig|units}` to be populated is now fixed.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
I had to install helm3 and re-generate the code once more time.
Also, one unit test needed a fix.

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Pull request merged**
