### PR TITLE
Switch to autoscaling.k8s.io/v1 for VPA object

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area os
/area auto-scaling
/kind enhancement
/os ubuntu

**What this PR does / why we need it**:
Switch to autoscaling.k8s.io/v1, as it allows for finer-grained configuration of `controlledResources` and `controlledValues` – you can e.g. configure VPA to only take care of requests an leave your limits alone. We have been doing this for all Gardener components to ensure we're not using outdated api versions for VPA.

**Release note**:

```other operator
Switch to autoscaling.k8s.io/v1 for VPA object
```

### CODE REVIEW

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Comment by MrBatschner** [comment]
@voelzmo Can you also run `make generate` and attach the resulting `example/controller-registration.yaml` to this PR?

**Comment by voelzmo** [comment]
@MrBatschner Done, thanks for the reminder!

**Review by MrBatschner — APPROVED** [review]
/lgtm

**Pull request merged**
